### ISSUE TITLE
CCS SPI LOG files

### ISSUE THREAD

**Issue by F1atline** [damienmaguire/BMW-i3-CCS#5]
Please, indicate were on signal diagram - MOSI, MISO, CLOCK, CS.
Thank you!

**Comment by damienmaguire** [comment]
If you open the captures with Saleae : https://www.saleae.com/
and select spi decoder , 16 bit transfer , cpol=1,cpha=1 and msb first it will auto detect the signals and give the option to save as a csv.

**Comment by F1atline** [comment]
Okay! Are you use Sealae Logic 2?

**Comment by F1atline** [comment]
In this case all data equal zero or error
![image](https://user-images.githubusercontent.com/20475876/141274062-e2bd0a5d-09fa-46be-b94d-3c4ca165a7da.png)
The settings
![image](https://user-images.githubusercontent.com/20475876/141274159-1f7b1ec5-0e23-468b-9e3a-bf9839259638.png)

**Comment by damienmaguire** [comment]
![2021-11-11 11 31 01](https://user-images.githubusercontent.com/9742117/141291289-8ac691b8-7995-41ad-af4e-87f9be0f9723.jpg)
![2021-11-11 11 31 33](https://user-images.githubusercontent.com/9742117/141291303-9503a7c7-5d26-4478-b7ef-a309404175d7.jpg)

**Comment by F1atline** [comment]
Thank you! Perfect!
